# Generated by Django 4.2 on 2024-03-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_onboardingmodule_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingtask',
            name='onboarding_file',
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='OnBoardingFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=256, null=True)),
                ('onboarding_file', models.FileField(blank=True, null=True, upload_to='onboarding_documents/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('task_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_boarding_task_files', to='onboarding.onboardingtask')),
            ],
        ),
    ]
