# Generated by Django 4.0.3 on 2023-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='visibility',
            field=models.CharField(blank=True, choices=[('VISIBLE_TO_ALL', 'Visible To All'), ('LIMITED_VISIBILITY', 'Limited Visibility')], help_text='It indicates the visibility to the employees', max_length=20, null=True, verbose_name='Visibility'),
        ),
    ]
