# Generated by Django 4.0.3 on 2023-10-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pss_calendar', '0003_remove_events_department_events_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidays',
            options={'verbose_name': 'Upload Holidays', 'verbose_name_plural': 'Upload Holidays'},
        ),
    ]
