# Generated by Django 4.0.3 on 2023-06-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='employeedepartment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeedepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeedepartment',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employeedepartment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeedepartment',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='EmployeeDepartment',
        ),
    ]
