# Generated by Django 4.0.3 on 2023-06-30 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='on_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
