# Generated by Django 4.0.3 on 2023-06-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0002_futuremodule_content_type'),
        ('payroll', '0005_activitylog_on_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='on_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRMSApp.companydetails'),
        ),
    ]
