# Generated by Django 4.0.3 on 2023-07-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_activitylog_on_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='updated_employee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
