# Generated by Django 4.0.3 on 2023-07-12 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0005_alter_employeedocumentationwork_document_description'),
        ('payroll', '0008_remove_employeesalaryadministrator_aadhar_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(blank=True, choices=[('Travel', 'Travel'), ('Hotel & Accomodation ', 'Hotel & Accomodation'), ('Food', 'Food'), ('Medical', 'Medical'), ('Telephone', 'Telephone'), ('Fuel', 'Fuel'), ('Imprest', 'Imprest'), ('Other', 'Other')], max_length=255, null=True)),
                ('expense_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('support_file', models.FileField(blank=True, null=True, upload_to='employee/reimburesement/')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(blank=True, choices=[('Travel', 'Travel'), ('Hotel & Accomodation ', 'Hotel & Accomodation'), ('Food', 'Food'), ('Medical', 'Medical'), ('Telephone', 'Telephone'), ('Fuel', 'Fuel'), ('Imprest', 'Imprest'), ('Other', 'Other')], max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_reimbursement', to='directory.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
