# Generated by Django 4.0.3 on 2023-07-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_alter_reimbursement_type_delete_reimbursementtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryinfo',
            name='monthly_tds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='salary_before_tds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='tds_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
