# Generated by Django 4.0.3 on 2023-07-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_employeesalaryinfo_monthly_tds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollinformation',
            name='a_basic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=70, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='a_others',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=70, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='advance_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='arrears',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=70, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='e_basic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='e_conv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='e_hra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='e_special_allow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='earned_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='edli_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='employee_esi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='employee_pf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='employer_esi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='employer_pf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='eps_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='leaves',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='lop',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='lop_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='monthly_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='monthly_incentive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=70, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='monthly_tds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='net_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='other_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='payable_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='pf_basic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='s_basic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='s_conv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='s_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='s_hra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='s_special_allow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='salary_before_tds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=70, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='special_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=70, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='t_basic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='tds_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='total_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='total_employee_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='total_employer_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='total_epf_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='total_esi_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='yearly_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
    ]
