# Generated by Django 4.0.3 on 2023-07-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_alter_esi_esi_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinformation',
            name='is_tds_fifty_percent',
            field=models.BooleanField(default=False),
        ),
    ]
