# Generated by Django 4.0.3 on 2023-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_payrollinformation_is_tds_fifty_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinformation',
            name='consider_tds_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='is_tds_percent_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
