# Generated by Django 4.0.3 on 2023-07-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_payrollinformation_month_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalaryinfo',
            name='monthly_tds',
        ),
    ]
