# Generated by Django 4.0.3 on 2023-07-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_remove_employeesalaryinfo_monthly_tds'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinformation',
            name='total_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=120, null=True),
        ),
    ]
