# Generated by Django 4.0.3 on 2023-08-07 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_alter_employeeworkdetails_employee_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0020_payrollinformation_total_earnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeComplianceNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('pf_num', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('uan_num', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('esi_num', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nominee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nominee_rel', models.CharField(blank=True, max_length=50, null=True)),
                ('nominee_dob', models.DateField(blank=True, null=True, verbose_name='nominee date of birth')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp_compliance_detail', to='directory.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryAdministrator',
        ),
    ]
