# Generated by Django 4.0.3 on 2023-08-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_reimbursement_employer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved_Paid', 'Approved_Paid'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='type',
            field=models.CharField(blank=True, choices=[('Travel', 'Travel'), ('Hotel_Accomodation', 'Hotel_Accomodation'), ('Food', 'Food'), ('Medical', 'Medical'), ('Telephone', 'Telephone'), ('Fuel', 'Fuel'), ('Imprest', 'Imprest'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
