# Generated by Django 4.0.3 on 2023-08-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_alter_reimbursement_status_alter_reimbursement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='other_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
