# Generated by Django 4.0.3 on 2023-08-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_reimbursement_other_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollinformation',
            name='paid_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='payrollinformation',
            name='working_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True),
        ),
    ]
