# Generated by Django 4.0.3 on 2023-08-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_payrollinformation_reimbursed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regime',
            name='regime_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
