# Generated by Django 4.0.3 on 2023-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_alter_regime_regime_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompliancenumbers',
            name='esi_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeecompliancenumbers',
            name='pf_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeecompliancenumbers',
            name='uan_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
