# Generated by Django 4.2 on 2023-10-02 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_alter_employeelops_leaves_encashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelops',
            name='comp_offs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
    ]
