# Generated by Django 4.2 on 2023-10-02 12:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0034_alter_employeelops_comp_offs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelops',
            name='comp_offs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
