# Generated by Django 4.2 on 2023-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_alter_employeelops_comp_offs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelops',
            name='comp_offs',
        ),
        migrations.AlterField(
            model_name='employeelops',
            name='leaves_encashed',
            field=models.PositiveIntegerField(blank=True, default=0.0, null=True),
        ),
    ]
