# Generated by Django 4.2 on 2023-10-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0037_employeeot_employeeot_unique_employee_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeot',
            name='created_from',
            field=models.CharField(blank=True, choices=[('hrms', 'hrms'), ('payroll', 'payroll')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeot',
            name='updated_from',
            field=models.CharField(blank=True, choices=[('hrms', 'hrms'), ('payroll', 'payroll')], max_length=50, null=True),
        ),
    ]
