# Generated by Django 4.0.3 on 2023-10-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_payrollinformation_salary_before_tds_constraint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollinformation',
            old_name='leaves_taxable_amount',
            new_name='leaves_encash_exemption_amount',
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='leaves_encash_taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=70, null=True),
        ),
    ]
