# Generated by Django 4.2 on 2023-10-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_payrollinformation_salary_before_tds_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payrollinformation',
            name='monthly_tds_constraint',
        ),
    ]
