# Generated by Django 4.0.3 on 2023-10-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_rename_leaves_taxable_amount_payrollinformation_leaves_encash_exemption_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinformation',
            name='overtime_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=70, null=True),
        ),
    ]
