# Generated by Django 4.0.3 on 2023-10-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_remove_payrollinformation_monthly_tds_constraint'),
        ('payroll', '0042_payrollinformation_overtime_days'),
    ]

    operations = [
    ]
