# Generated by Django 4.2 on 2023-10-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_merge_20231006_1900'),
        ('payroll', '0043_merge_20231006_1905'),
    ]

    operations = [
    ]
