# Generated by Django 4.0.3 on 2023-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('payroll', '0047_remove_employeelops_unique_employee_lop'),
        ('payroll', '0047_remove_employeetds_created_by_and_more'),
    ]

    operations = [
        # migrations.AddConstraint(
        #     model_name='employeelops',
        #     constraint=models.UniqueConstraint(fields=('employee', 'lop_month_year'), name='unique_employee_lop'),
        # ),
        migrations.RemoveField(
            model_name='employeeot',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeeot',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeot',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='EmployeeLops',
        ),
        migrations.DeleteModel(
            name='EmployeeOT',
        ),
    ]
