# Generated by Django 4.0.3 on 2023-10-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0048_remove_employeeot_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
