# Generated by Django 4.2 on 2023-11-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0051_payrollinformation_fixed_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinformation',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
