# Generated by Django 4.2 on 2023-12-01 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0052_payrollinformation_is_on_hold'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('leave_type', models.CharField(blank=True, choices=[('sick_leave', 'sick_leave'), ('casual_leave', 'casual_leave'), ('privilege_leave', 'privilege_leave')], max_length=28, null=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('leaves_added', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('leaves_availed', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='payroll_leaves',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollleaves'),
        ),
    ]
