# Generated by Django 4.2 on 2023-12-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0053_payrollleaves_payrollinformation_payroll_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompliancenumbers',
            name='health_insurence',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('ESI', 'ESI'), ('NEED_TO_CHECK', 'NEED_TO_CHECK')], default='NO', max_length=16),
        ),
        migrations.AddField(
            model_name='employeecompliancenumbers',
            name='insurence_date',
            field=models.DateField(blank=True, null=True, verbose_name='insurence Date'),
        ),
        migrations.AddField(
            model_name='employeecompliancenumbers',
            name='insurence_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/'),
        ),
    ]
