# Generated by Django 4.0.3 on 2024-01-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0054_employeecompliancenumbers_health_insurence_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payrollinformation',
            name='salary_before_tds_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='payrollinformation',
            name='tds_left_constraint',
        ),
    ]
