# Generated by Django 4.0.3 on 2024-02-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0056_reminderdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompliancenumbers',
            name='health_insurence',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('ESI', 'ESI'), ('NEED_TO_CHECK', 'NEED_TO_CHECK')], max_length=16, null=True),
        ),
    ]
