# Generated by Django 4.2 on 2024-03-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0058_epfemployees'),
        ('payroll', '0059_alter_payslipfields_fields_list'),
    ]

    operations = [
    ]
