# Generated by Django 4.2 on 2024-03-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0060_employeepayrollonhold'),
        ('payroll', '0060_merge_20240302_1722'),
    ]

    operations = [
    ]
