# Generated by Django 4.2 on 2024-03-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0062_alter_employeepayrollonhold_hold_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinformation',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='compensation_for_esi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=120, null=True),
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='days_present',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='esi_employee_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=120, null=True),
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='holidays',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='staff_loan_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=120, null=True),
        ),
        migrations.AddField(
            model_name='payrollinformation',
            name='weekly_offs',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=50, null=True),
        ),
    ]
