# Generated by Django 4.2 on 2024-03-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0063_payrollinformation_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinformation',
            name='other_additions',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=120, null=True),
        ),
    ]
