# Generated by Django 4.2 on 2024-03-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0065_payrollinformation_mode_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollinformation',
            name='esi_employee_contribution',
        ),
    ]
