# Generated by Django 4.2 on 2024-04-01 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0040_alter_employeesalarydetails_previous_income_and_more'),
        ('payroll', '0066_remove_payrollinformation_esi_employee_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsiResignationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('esi_resignation_status', models.CharField(choices=[('Left Service 2', 'Left Service 2'), ('Retired 3', 'Retired 3'), ('Out of Coverage 4', 'Out of Coverage 4'), ('Expired 5', 'Expired 5'), ('Non Implemented area 6', 'Non Implemented area 6'), ('Compliance by Immediate Employer 7', 'Compliance by Immediate Employer 7'), ('Suspension of work 8', 'Suspension of work 8'), ('Strike/Lockout 9', 'Strike/Lockout 9'), ('Retrenchment 10', 'Retrenchment 10'), ('No Work 11', 'No Work 11'), ('Doesnt Belong To This Employer 12', 'Doesnt Belong To This Employer 12'), ('Duplicate IP 13', 'Duplicate IP 13')], max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp_esi_resignation', to='directory.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
