# Generated by Django 4.2 on 2024-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0067_esiresignationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esiresignationdetails',
            name='esi_resignation_status',
            field=models.CharField(choices=[('Left Service 2', '2'), ('Retired 3', '3'), ('Out of Coverage 4', '4'), ('Expired 5', '5'), ('Non Implemented area 6', '6'), ('Compliance by Immediate Employer 7', '7'), ('Suspension of work 8', '8'), ('Strike/Lockout 9', '9'), ('Retrenchment 10', '10'), ('No Work 11', '11'), ('Doesnt Belong To This Employer 12', '12'), ('Duplicate IP 13', '13')], max_length=255),
        ),
    ]
