# Generated by Django 4.2 on 2024-04-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0069_alter_esiresignationdetails_esi_resignation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollinformation',
            name='current_month_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=120, null=True),
        ),
    ]
