# Generated by Django 4.0.3 on 2023-06-22 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('formtype', models.CharField(help_text='Form Choices', max_length=100, verbose_name='Form Choices')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Form Choice',
                'verbose_name_plural': 'Form Choices',
            },
        ),
        migrations.CreateModel(
            name='SubFormChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('formtype', models.CharField(help_text='Form Choices', max_length=100, verbose_name='Form Choices')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('parentform', models.ForeignKey(help_text='Parent Form from form choices', on_delete=django.db.models.deletion.CASCADE, related_name='form_choices', to='investment_declaration.formchoices', verbose_name='Parent Form')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'SUb Form Choice',
                'verbose_name_plural': 'Sub Form Choices',
            },
        ),
        migrations.CreateModel(
            name='InvestmentDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('regime_type', models.PositiveSmallIntegerField(choices=[(10, 'Old Tax Regime'), (20, 'New Tax Regime')], help_text='It indicates the employee choose which regime he belongs to.', verbose_name='Regime Type')),
                ('declaration_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Employee Total Declaration Amount', max_digits=12, verbose_name='Total Declaration Amount')),
                ('income_from_previous_employer', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Income From Previous Employer', max_digits=12, null=True, verbose_name='Income From Previous Employer')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Employee Total Approved Amount', max_digits=12, verbose_name='Total Approved Amount')),
                ('final_declared_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Employee Total Final Declared Amount', max_digits=12, verbose_name='Total Final Declared Amount')),
                ('final_approved_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Employee Total Final Approved Amount', max_digits=12, verbose_name='Total Final Approved Amount')),
                ('savings_after_ctc', models.DecimalField(decimal_places=2, default=0.0, help_text='Employee Savings After CTC', max_digits=12, verbose_name='Savings After CTC')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Saved'), (20, 'Submitted'), (30, 'Re Submitted'), (40, 'Cancel'), (50, 'Revoked'), (60, 'Approved'), (70, 'Approve_revoked'), (80, 'Declined')], help_text='Approval or Submit status representations', null=True, verbose_name='Form Status')),
                ('start_year', models.IntegerField(blank=True, verbose_name='Declaration Start Year')),
                ('end_year', models.IntegerField(blank=True, verbose_name='Declaration End Year')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approved Date')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(help_text='Employe Primary Key Of Employee', on_delete=django.db.models.deletion.CASCADE, to='directory.employee', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Investment Declaration',
                'verbose_name_plural': 'Investment Declarations',
                'unique_together': {('employee', 'start_year', 'end_year')},
            },
        ),
        migrations.CreateModel(
            name='DeclarationForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('declared_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Employee Savings Declared Amount', max_digits=12, verbose_name='Declared Amount')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Employee Approved Amount', max_digits=12, verbose_name='Approved Amount')),
                ('final_declared_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Employee Final Declared Amount', max_digits=12, verbose_name='Employee Final Declared Amount')),
                ('final_approved_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Employee Final Approved Amount', max_digits=12, verbose_name='Employee Final Approved Amount')),
                ('no_of_attachments', models.IntegerField(blank=True, default=0, null=True, verbose_name='Form Attachments Count')),
                ('comments_from_employee', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('comments_from_employer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('declaration', models.ForeignKey(help_text='Relation to the declarations', on_delete=django.db.models.deletion.CASCADE, related_name='declaration_forms', to='investment_declaration.investmentdeclaration', verbose_name='Investment Declaration')),
                ('parentform_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment_declaration.formchoices', verbose_name='Parent Form Type')),
                ('subform_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment_declaration.subformchoices', verbose_name='Sub Form Type')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Declaration Form',
                'verbose_name_plural': 'Declaration Forms',
                'ordering': ('created_at',),
                'unique_together': {('declaration', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='Investment_Attachments')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('declaration_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_declaration.declarationforms')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Attachments',
                'verbose_name_plural': 'Attachmnets',
            },
        ),
    ]
