# Generated by Django 4.0.3 on 2023-07-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0002_investmentdeclaration_tds_from_previous_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='investment_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment_declaration.investmentdeclaration'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='declaration_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment_declaration.declarationforms'),
        ),
    ]
