# Generated by Django 4.0.3 on 2023-07-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0003_attachments_investment_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdeclaration',
            name='admin_resubmit_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'Re Submitted')], null=True),
        ),
    ]
