# Generated by Django 4.0.3 on 2023-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0004_investmentdeclaration_admin_resubmit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdeclaration',
            name='admin_resubmit_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(60, 'Approved'), (50, 'Revoked'), (30, 'Re Submitted')], null=True),
        ),
        migrations.AlterField(
            model_name='investmentdeclaration',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Saved'), (20, 'Submitted'), (30, 'Re Submitted'), (40, 'Cancel'), (50, 'Revoked'), (60, 'Approved'), (70, 'Approve_revoked'), (80, 'Declined'), (90, 'Final_Approved')], help_text='Approval or Submit status representations', null=True, verbose_name='Form Status'),
        ),
    ]
