# Generated by Django 4.0.3 on 2023-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0005_alter_investmentdeclaration_admin_resubmit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarationforms',
            name='final_declared_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Employee Final Declared Amount', max_digits=12, null=True, verbose_name='Employee Final Declared Amount'),
        ),
    ]
