# Generated by Django 4.0.3 on 2023-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0006_alter_declarationforms_final_declared_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdeclaration',
            name='admin_resubmit_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(60, 'Approved'), (50, 'Revoked'), (30, 'Re Submitted'), (10, 'Saved')], null=True),
        ),
    ]
