# Generated by Django 4.0.3 on 2023-09-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0007_alter_investmentdeclaration_admin_resubmit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdeclaration',
            name='admin_resubmit_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(60, 'Approved'), (50, 'Revoked'), (30, 'Re Submitted'), (90, 'Final_Approved'), (10, 'Saved')], null=True),
        ),
    ]
