# Generated by Django 4.0.3 on 2023-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0009_alter_investmentdeclaration_admin_resubmit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdeclaration',
            name='submitted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submitted Date'),
        ),
    ]
