# Generated by Django 4.0.3 on 2023-10-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0010_investmentdeclaration_submitted_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentdeclaration',
            options={'verbose_name': 'Saving Declaration Form', 'verbose_name_plural': 'Saving Declaration Form'},
        ),
    ]
