# Generated by Django 4.0.3 on 2023-11-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0011_alter_investmentdeclaration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdeclaration',
            name='access_to_select_regime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentdeclaration',
            name='freeze_declared_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investmentdeclaration',
            name='freeze_final_declared_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investmentdeclaration',
            name='last_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Submission Date'),
        ),
    ]
