# Generated by Django 4.0.3 on 2023-11-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_declaration', '0012_investmentdeclaration_access_to_select_regime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdeclaration',
            name='regime_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Old Tax Regime'), (20, 'New Tax Regime')], help_text='It indicates the employee choose which regime he belongs to.', null=True, verbose_name='Regime Type'),
        ),
    ]
