# Generated by Django 4.0.3 on 2023-06-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('HRMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuremodule',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'directory'), ('model', 'Employee')), models.Q(('app_label', 'company'), ('model', 'Department')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
    ]
