# Generated by Django 4.0.3 on 2023-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0002_futuremodule_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='payslip_watermark_img_abc',
            field=models.FileField(blank=True, null=True, upload_to='company_images/'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='watermark_status_abc',
            field=models.BooleanField(default=False, help_text='True will treated as Show. False will treate as Hide.'),
        ),
    ]
