# Generated by Django 4.0.3 on 2023-07-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0003_companydetails_payslip_watermark_img_abc_and_more'),
    ]

    operations = [  
        migrations.RemoveField(
            model_name='companydetails',
            name='watermark_status_abc',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='watermark_status',
            field=models.IntegerField(choices=[(1, 'Show'), (2, 'Hide')], default=2, help_text='1 will treated as Show. 2 will treate as Hide.'),
        ),
    ]
