# Generated by Django 4.0.3 on 2023-07-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0004_rename_payslip_watermark_img_abc_companydetails_payslip_watermark_img_and_more'),
    ]

 