# Generated by Django 4.0.3 on 2023-07-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0005_rename_payslip_watermark_img_abc_companydetails_payslip_watermark_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='payslip_watermark_img_abc',
            new_name='payslip_watermark',
        ),
    ]
