# Generated by Django 4.0.3 on 2023-09-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='is_brand_name_updated',
            field=models.BooleanField(default=False),
        ),
    ]
