# Generated by Django 4.2 on 2023-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0014_companydetails_decimals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('Cybersecurity', 'Cybersecurity'), ('Software', 'Software'), ('Hardware and equipment', 'Hardware and equipment'), ('Artificial intelligence', 'Artificial intelligence'), ('Education and training', 'Education and training'), ('Data services', 'Data services'), ('Business services', 'Business services'), ('Public infrastructure', 'Public infrastructure'), ('Telecommunications', 'Telecommunications'), ('IT consulting', 'IT consulting'), ('Finance', 'Finance'), ('Simulation', 'Simulation'), ('Robotics', 'Robotics'), ('Creative services', 'Creative services'), ('Research and development', 'Research and development'), ('Energy', 'Energy'), ('Medical', 'Medical'), ('Sales and marketing', 'Sales and marketing'), ('Gaming', 'Gaming'), ('Consumer products and services', 'Consumer products and services'), ('others', 'others')], max_length=80, null=True),
        ),
    ]
