# Generated by Django 4.0.3 on 2024-01-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0016_companydetails_payslip_hr_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='payslip_hr_email',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='payslip_hr_phone',
        ),
    ]
