# Generated by Django 4.0.3 on 2024-02-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0019_companycustomizedconfigurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycustomizedconfigurations',
            name='can_payroll_auto_deactivate_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
