# Generated by Django 4.0.3 on 2024-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0020_companycustomizedconfigurations_can_payroll_auto_deactivate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycustomizedconfigurations',
            name='compoff_apply_days_excemption',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companycustomizedconfigurations',
            name='compoff_apply_days_excemption_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
