# Generated by Django 4.2 on 2024-02-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0020_companycustomizedconfigurations_can_payroll_auto_deactivate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycustomizedconfigurations',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_config', to='HRMSApp.companydetails'),
        ),
    ]
