# Generated by Django 4.0.3 on 2024-02-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0021_alter_companycustomizedconfigurations_company'),
        ('HRMSApp', '0021_companycustomizedconfigurations_compoff_apply_days_excemption_and_more'),
    ]

    operations = [
    ]
