# Generated by Django 4.2 on 2024-02-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0023_companycustomizedconfigurations_max_days_to_utilize_compoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='is_multitenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='multitenant_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
