# Generated by Django 4.2 on 2024-02-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0024_companydetails_is_multitenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='is_multitenant_role',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
