# Generated by Django 4.2 on 2024-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0026_multitenantcompanies_companydetails_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='company_uid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
