# Generated by Django 4.2 on 2024-03-08 07:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0028_companydetails_child_company_uids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='child_company_uids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
