# Generated by Django 4.0.3 on 2023-06-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0002_designations_department_designations_sub_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designations',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_dep_desig', to='company_profile.subdepartments'),
        ),
    ]
