# Generated by Django 4.0.3 on 2023-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0003_alter_designations_sub_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutorydetails',
            name='other_entity_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
