# Generated by Django 4.0.3 on 2023-08-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0004_statutorydetails_other_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True)),
                ('end_point', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=256, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, null=True)),
                ('method', models.CharField(blank=True, max_length=200, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('is_success_entry', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
