# Generated by Django 4.0.3 on 2023-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0005_loggingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingrecord',
            name='old_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
