# Generated by Django 4.2 on 2023-09-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0006_loggingrecord_old_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designations',
            name='department',
        ),
        migrations.RemoveField(
            model_name='designations',
            name='sub_department',
        ),
    ]
