# Generated by Django 4.2 on 2023-10-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0007_loggingrecord_user'),
        ('company_profile', '0007_remove_designations_department_and_more'),
    ]

    operations = [
    ]
