# Generated by Django 4.2 on 2023-10-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0008_merge_20231002_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='annoucement_image',
            field=models.FileField(blank=True, null=True, upload_to='company_annoucement_files/'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
