# Generated by Django 4.2 on 2023-10-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0009_announcements_annoucement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='departments',
            field=models.ManyToManyField(default=[], related_name='announcements_departments', to='company_profile.departments'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='visibility',
            field=models.CharField(blank=True, choices=[('VISIBLE_TO_ALL', 'Visible To All'), ('LIMITED_VISIBILITY', 'Limited Visibility')], max_length=20, null=True),
        ),
    ]
