# Generated by Django 4.0.3 on 2023-10-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0010_announcements_departments_announcements_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutorydetails',
            name='tds_circle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
