# Generated by Django 4.0.3 on 2023-10-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0011_statutorydetails_tds_circle_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditordetails',
            options={'verbose_name': 'Auditors', 'verbose_name_plural': 'Auditors'},
        ),
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name': 'Bank Account Info', 'verbose_name_plural': 'Bank Account Info'},
        ),
        migrations.AlterModelOptions(
            name='companydirectordetails',
            options={'verbose_name': 'Directors', 'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='customaddressdetails',
            options={'verbose_name': 'Custom Address', 'verbose_name_plural': 'Custom Address'},
        ),
        migrations.AlterModelOptions(
            name='designations',
            options={'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='loggingrecord',
            options={'verbose_name': 'Audit Report', 'verbose_name_plural': 'Audit Report'},
        ),
        migrations.AlterModelOptions(
            name='secretarydetails',
            options={'verbose_name': 'Company Secretary', 'verbose_name_plural': 'Company Secretary'},
        ),
        migrations.AlterModelOptions(
            name='statutorydetails',
            options={'verbose_name': 'Over View', 'verbose_name_plural': 'Over View'},
        ),
        migrations.AddField(
            model_name='loggingrecord',
            name='model_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
