# Generated by Django 4.2 on 2023-10-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0012_alter_auditordetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='annoucement_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Announcement description'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='announcement_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Announcement Title'),
        ),
    ]
