# Generated by Django 4.2 on 2023-10-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0013_announcements_annoucement_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='annoucement',
        ),
    ]
