# Generated by Django 4.2 on 2023-12-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0014_remove_announcements_annoucement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='announcement_type',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('TIKKER', 'Tikker')], default='ANNOUNCEMENT', max_length=48),
        ),
    ]
