# Generated by Django 4.0.3 on 2024-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0016_companypolicytypes_companypolicydocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='annoucement_image',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='company_annoucement_files/'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='file_path',
            field=models.FileField(max_length=512, upload_to='company_policy_files/'),
        ),
    ]
