# Generated by Django 4.0.3 on 2023-07-19 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_remove_attendancerules_enable_auto_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamolyhistory',
            name='deducted_from',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='AutoDeductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('request_date', models.DateField(help_text='Employee Anomalie Date', verbose_name='Anomaly request date')),
                ('choice', models.PositiveSmallIntegerField(choices=[('IN_TIME_BREACH', 'In Time'), ('OUT_TIME_BREACH', 'Out Time'), ('FULL_DAY_WD_BREACH', 'Full Day Work Duration'), ('HALF_DAY_WD_BREACH', 'Half Day Work Duration'), ('MAX_BREAK_DURATION_BREACH', 'Break Duration'), ('MAX_TOTAL_BREAKS_BREACH', 'No Of Breaks')])),
                ('result', models.CharField(blank=True, max_length=20, null=True, verbose_name='result')),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('is_anamoly_created', models.BooleanField(default=False)),
                ('deducted_from', models.CharField(blank=True, max_length=256, null=True)),
                ('clock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employeecheckinoutdetails')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['request_date'],
            },
        ),
    ]
