# Generated by Django 4.0.3 on 2023-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_anamolyhistory_deducted_from_autodeductionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeductionhistory',
            name='request_date',
            field=models.DateField(),
        ),
    ]
