# Generated by Django 4.0.3 on 2023-07-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_autodeductionhistory_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodeductionhistory',
            name='choice',
            field=models.CharField(choices=[('IN_TIME_BREACH', 'In Time'), ('OUT_TIME_BREACH', 'Out Time'), ('FULL_DAY_WD_BREACH', 'Full Day Work Duration'), ('HALF_DAY_WD_BREACH', 'Half Day Work Duration'), ('MAX_BREAK_DURATION_BREACH', 'Break Duration'), ('MAX_TOTAL_BREAKS_BREACH', 'No Of Breaks')], max_length=256),
        ),
    ]
