# Generated by Django 4.0.3 on 2023-07-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_autodeductionhistory_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecheckinoutdetails',
            name='is_logged_out',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
