# Generated by Django 4.0.3 on 2023-07-27 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0006_employeeresignationdetails_last_working_day'),
        ('attendance', '0006_employeecheckinoutdetails_is_logged_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMonthlyAttendanceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('attendance_data', models.JSONField(blank=True, default=dict, null=True)),
                ('present_days', models.IntegerField(default=0)),
                ('leaves_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('anamoly_count', models.IntegerField(default=0)),
                ('halfday_count', models.IntegerField(default=0)),
                ('lop_count', models.IntegerField(default=0)),
                ('updated_lop_count', models.IntegerField(default=0)),
                ('penalty_details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='montly_attendance', to='directory.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
