# Generated by Django 4.0.3 on 2023-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_updated_lop_count_employeemonthlyattendancerecords_updated_hr_lop_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemonthlyattendancerecords',
            name='absent_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeemonthlyattendancerecords',
            name='anamoly_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeemonthlyattendancerecords',
            name='halfday_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeemonthlyattendancerecords',
            name='leaves_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeemonthlyattendancerecords',
            name='lop_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeemonthlyattendancerecords',
            name='present_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeemonthlyattendancerecords',
            name='updated_hr_lop_count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employeemonthlyattendancerecords',
            name='updated_manager_lop_count',
            field=models.FloatField(default=0.0),
        ),
    ]
