# Generated by Django 4.0.3 on 2023-07-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_employeemonthlyattendancerecords_absent_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamolyhistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Approved'), (20, 'Pending'), (30, 'Processing'), (40, 'Rejected')], default=20, help_text='It indicates the approval status', verbose_name='Approval Status'),
        ),
    ]
