# Generated by Django 4.0.3 on 2023-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_anamolyhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemonthlyattendancerecords',
            name='is_hr_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeemonthlyattendancerecords',
            name='is_manager_updated',
            field=models.BooleanField(default=False),
        ),
    ]
