# Generated by Django 4.0.3 on 2023-08-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_employeemonthlyattendancerecords_is_hr_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerules',
            name='minimum_minitues_to_over_time',
            field=models.IntegerField(default=60),
        ),
    ]
