# Generated by Django 4.0.3 on 2023-08-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancerules_minimum_minitues_to_over_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerules',
            name='minimum_minitues_to_over_time',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
