# Generated by Django 4.0.3 on 2023-09-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_vgattendancelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerulesettings',
            name='attendance_start_month',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
