# Generated by Django 4.0.3 on 2023-09-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_alter_employee_is_sign_up'),
        ('attendance', '0016_attendancerulesettings_attendance_start_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemonthlyattendancerecords',
            name='hr_hosted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hr_updated_montly_attendance', to='directory.employee'),
        ),
        migrations.AddField(
            model_name='employeemonthlyattendancerecords',
            name='manager_hosted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_updated_montly_attendance', to='directory.employee'),
        ),
    ]
