# Generated by Django 4.0.3 on 2023-09-15 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0010_alter_companydetails_is_brand_name_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0017_employeemonthlyattendancerecords_hr_hosted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidateNotificationDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee_start_date', models.DateField(blank=True, null=True)),
                ('employee_end_date', models.DateField(blank=True, null=True)),
                ('reporting_manager_start_date', models.DateField(blank=True, null=True)),
                ('reporting_manager_end_date', models.DateField(blank=True, null=True)),
                ('hr_manager_start_date', models.DateField(blank=True, null=True)),
                ('hr_manager_end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidate_notification_date', to='HRMSApp.companydetails')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Consolidate Notification Dates',
                'verbose_name_plural': 'Consolidate Notification Dates',
            },
        ),
    ]
