# Generated by Django 4.0.3 on 2023-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_consolidatenotificationdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerulesettings',
            name='attendance_paycycle_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
