# Generated by Django 4.0.3 on 2023-09-18 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_employeedocuments_document_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMSApp', '0010_alter_companydetails_is_brand_name_updated'),
        ('attendance', '0019_attendancerulesettings_attendance_paycycle_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceShiftsSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('calendar_type', models.CharField(blank=True, choices=[('calendaryear', 'CalendarYear'), ('financialyear', 'FinancialYear')], max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_shiftsetup_updated', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSApp.companydetails', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('session_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.sessionyear')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Attendance Shifts Setup',
                'verbose_name_plural': 'Attendance Shifts Setup',
            },
        ),
    ]
