# Generated by Django 4.0.3 on 2023-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_attendanceshiftssetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerulesettings',
            name='calendar_type',
            field=models.CharField(blank=True, choices=[('calendaryear', 'CalendarYear'), ('financialyear', 'FinancialYear')], max_length=50, null=True),
        ),
    ]
