# Generated by Django 4.0.3 on 2023-09-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_alter_anamolyhistory_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerules',
            name='comp_off_full_day_work_duration',
            field=models.CharField(blank=True, default='00:00:00', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='attendancerules',
            name='comp_off_half_day_work_duration',
            field=models.CharField(blank=True, default='00:00:00', max_length=16, null=True),
        ),
    ]
