# Generated by Django 4.0.3 on 2023-09-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_attendancerules_comp_off_full_day_work_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerules',
            name='minimum_hours_to_consider_ot',
            field=models.CharField(blank=True, default='0:0', max_length=8, null=True),
        ),
    ]
