# Generated by Django 4.0.3 on 2023-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_attendancerules_minimum_hours_to_consider_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerules',
            name='comp_off_full_day_work_duration',
            field=models.CharField(blank=True, default='0:0', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerules',
            name='comp_off_half_day_work_duration',
            field=models.CharField(blank=True, default='0:0', max_length=16, null=True),
        ),
    ]
