# Generated by Django 4.0.3 on 2023-09-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_alter_attendancerules_comp_off_full_day_work_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemonthlyattendancerecords',
            name='overtime_count',
            field=models.FloatField(default=0.0),
        ),
    ]
