# Generated by Django 4.0.3 on 2023-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_employeemonthlyattendancerecords_overtime_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecheckinoutdetails',
            name='compoff_added',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
