# Generated by Django 4.0.3 on 2023-09-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_employeecheckinoutdetails_compoff_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemonthlyattendancerecords',
            name='is_payroll_run',
            field=models.BooleanField(default=False),
        ),
    ]
