# Generated by Django 4.0.3 on 2023-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_alter_employeemonthlyattendancerecords_is_payroll_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerules',
            name='selected_time_zone',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=256, null=True),
        ),
    ]
