# Generated by Django 4.0.3 on 2023-10-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_attendancerules_selected_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemonthlyattendancerecords',
            name='leaves_encash_count',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
