# Generated by Django 4.2 on 2023-11-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_alter_attendancerulesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyloggerAttendanceLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=25)),
                ('system_on', models.DateTimeField(blank=True, null=True)),
                ('system_off', models.DateTimeField(blank=True, null=True)),
                ('break_duration', models.IntegerField(blank=True, null=True)),
                ('system_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('internet_ip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
