# Generated by Django 4.2 on 2023-11-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_keyloggerattendancelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyloggerattendancelogs',
            name='system_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
