# Generated by Django 4.2 on 2023-12-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_employeemonthlyattendancerecords_hr_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyloggerattendancelogs',
            name='internet_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='keyloggerattendancelogs',
            name='system_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
