# Generated by Django 4.2 on 2023-12-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_employeesystemmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyloggerattendancelogs',
            name='break_cause',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
