# Generated by Django 4.2 on 2024-01-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0039_keyloggerattendancelogs_break_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyloggerattendancelogs',
            name='system_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
