# Generated by Django 4.0.3 on 2024-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0041_alter_keyloggerattendancelogs_break_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecheckinoutdetails',
            name='checkin_location',
            field=models.CharField(blank=True, choices=[('Work From Home', 'Work From Home'), ('Work From Remote', 'Work From Remote'), ('Work From Office', 'Work From Office')], default='Work From Office', max_length=32, null=True),
        ),
    ]
