# Generated by Django 4.2 on 2024-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0043_vgattendancelogs_attendance_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecheckinoutdetails',
            name='absent_period',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
