# Generated by Django 4.2 on 2024-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0044_consolidatebutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemonthlyattendancerecords',
            name='is_cron_run',
            field=models.BooleanField(default=False),
        ),
    ]
