# Generated by Django 4.0.3 on 2024-04-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0046_employeecheckinoutdetails_absent_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecheckinoutdetails',
            name='employee_selfie',
            field=models.FileField(blank=True, help_text='Employee Selfie to identify', max_length=512, null=True, upload_to='emplyee_attendance_selfie/', verbose_name='Employee Selfie'),
        ),
    ]
