# Generated by Django 4.0.3 on 2023-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_tickect_raised_by_alter_tickect_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickect',
            name='category',
            field=models.CharField(choices=[('billingissue', 'BillingIssue'), ('accessissue', 'AccessIssue'), ('payrollissue', 'PayrollIssue')], default='', max_length=28),
        ),
    ]
