# Generated by Django 4.0.3 on 2023-08-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_tickect_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickect',
            name='category',
            field=models.CharField(choices=[('billingissue', 'BillingIssue'), ('accessissue', 'AccessIssue'), ('payrollissue', 'PayrollIssue')], default='', max_length=28),
        ),
    ]
