# Generated by Django 4.0.3 on 2023-06-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0001_initial'),
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicetype',
            name='content_type',
        ),
        migrations.AddField(
            model_name='choicetype',
            name='company',
            field=models.ForeignKey(default=None, help_text='Related Company Choices', on_delete=django.db.models.deletion.CASCADE, to='HRMSApp.companydetails', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
