# Generated by Django 4.0.3 on 2023-08-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_tickect_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickect',
            name='category',
        ),
    ]
