# Generated by Django 4.0.3 on 2023-07-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaverulerelation',
            name='earned_leaves',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Earned Leaves'),
        ),
        migrations.AlterField(
            model_name='employeeleaverulerelation',
            name='penalty_deduction',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Penalty Deducted Leaves'),
        ),
        migrations.AlterField(
            model_name='employeeleaverulerelation',
            name='remaining_leaves',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Balance Leaves'),
        ),
        migrations.AlterField(
            model_name='employeeleaverulerelation',
            name='used_lop_leaves',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Used Loss Of Pay Leaves', max_digits=7, verbose_name='LOP Leaves'),
        ),
        migrations.AlterField(
            model_name='employeeleaverulerelation',
            name='used_so_far',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Applied Leaves'),
        ),
    ]
