# Generated by Django 4.0.3 on 2023-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_alter_employeeleaverulerelation_earned_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveshistory',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_docs/'),
        ),
    ]
