# Generated by Django 4.0.3 on 2023-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_alter_leaveshistory_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveshistory',
            name='no_of_leaves_applied',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Count of applied leaves', max_digits=7, verbose_name='No Of Leaves'),
        ),
    ]
