# Generated by Django 4.0.3 on 2023-10-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_alter_leaveshistory_no_of_leaves_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverules',
            name='all_remaining_leaves_for_encash',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='leaverules',
            name='is_leave_encashment_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='leaverules',
            name='max_leaves_to_encash',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
