# Generated by Django 4.0.3 on 2023-10-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_leaverules_all_remaining_leaves_for_encash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleaverulerelation',
            options={'verbose_name': 'Assign Leave Rules', 'verbose_name_plural': 'Assign Leave Rules'},
        ),
        migrations.AlterModelOptions(
            name='employeeworkrulerelation',
            options={'verbose_name': 'Assign Work Week', 'verbose_name_plural': 'Assign Work Week'},
        ),
        migrations.AlterModelOptions(
            name='leaverules',
            options={'verbose_name': 'Create Leave Rule', 'verbose_name_plural': 'Create Leave Rules'},
        ),
        migrations.AlterModelOptions(
            name='leaverulesettings',
            options={'verbose_name': 'Leaves Setup', 'verbose_name_plural': 'Leaves Setup'},
        ),
        migrations.AlterModelOptions(
            name='workrulechoices',
            options={'verbose_name': 'Work Week', 'verbose_name_plural': 'Work Weeks'},
        ),
        migrations.AlterModelOptions(
            name='workrules',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'Create Work Week', 'verbose_name_plural': 'Create Work Week'},
        ),
    ]
