# Generated by Django 4.0.3 on 2023-10-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_alter_employeeleaverulerelation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveshistory',
            name='is_revoked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
