# Generated by Django 4.0.3 on 2024-01-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_leaveshistory_is_revoked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeleaverulerelation',
            unique_together=set(),
        ),
    ]
