# Generated by Django 4.0.3 on 2024-01-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_alter_employeeleaverulerelation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverules',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverules',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
