# Generated by Django 4.0.3 on 2024-01-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_leaverules_valid_from_leaverules_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverules',
            name='max_leaves_allowed_in_month',
            field=models.FloatField(blank=True, default=4, null=True, verbose_name='Max Allowed Leaves Per Month'),
        ),
    ]
