# Generated by Django 4.0.3 on 2024-01-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0018_alter_leaverules_max_leaves_allowed_in_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverules',
            name='includes_check_in_leave',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
