# Generated by Django 4.0.3 on 2024-02-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_leaverules_includes_check_in_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveshistory',
            name='is_backdated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
