# Generated by Django 4.0.3 on 2024-02-04 05:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_leaverules_includes_check_in_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaverulerelation',
            name='compoff_added_details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), default=list, size=None),
        ),
    ]
