# Generated by Django 4.2 on 2024-02-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_employeeleaverulerelation_compoff_added_details'),
        ('leave', '0020_leaveshistory_is_backdated'),
    ]

    operations = [
    ]
