# Generated by Django 4.0.3 on 2023-07-07 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_approved_by', models.JSONField(default=dict)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('payment_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('pla', 'Platinum'), ('gol', 'Gold'), ('sil', 'Silver')], max_length=5)),
                ('price', models.FloatField()),
                ('num_of_employees', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=256)),
                ('card_num', models.CharField(max_length=256)),
                ('ifsc', models.CharField(max_length=256)),
                ('payment_type', models.CharField(choices=[('debitcard', 'DebitCard')], max_length=20)),
                ('billing_address', models.CharField(default='', max_length=256)),
                ('address_line1', models.CharField(default='', max_length=256)),
                ('address_line2', models.CharField(default='', max_length=256)),
                ('state', models.CharField(default='', max_length=256)),
                ('country', models.CharField(default='', max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=256)),
                ('user_details', models.CharField(blank=True, max_length=256, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('bankname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.transactionbankdetails')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billing')),
                ('plan_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='billing.plandetail')),
            ],
        ),
    ]
