# Generated by Django 4.0.3 on 2023-08-02 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_payment_approved_by_billing_payment_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('premium', 'premium'), ('enterprise', 'enterprise'), ('basic', 'basic')], max_length=28)),
                ('price', models.FloatField()),
                ('num_of_employees', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_updated_by',
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_approved_by',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='plan_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='billing.plandetail'),
        ),
    ]
