# Generated by Django 4.0.3 on 2023-08-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plandetail_remove_billing_payment_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='payment_approved_by',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='plan_type',
            field=models.CharField(choices=[('pla', 'Platinum'), ('gol', 'Gold'), ('sil', 'Silver')], max_length=5),
        ),
    ]
