# Generated by Django 4.0.3 on 2023-08-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_billing_payment_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='plan_type',
            field=models.CharField(choices=[('premium', 'premium'), ('enterprise', 'enterprise'), ('basic', 'basic')], max_length=28),
        ),
    ]
