# Generated by Django 4.0.3 on 2023-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_rename_payment_approved_by_billing_payment_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='plan_details',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
