# Generated by Django 4.0.3 on 2024-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_transactiondetails_plan_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='plan_type',
            field=models.CharField(choices=[('HRMS', 'hrms'), ('PAYROLL', 'payroll'), ('INTEGRATED', 'integrated')], max_length=28),
        ),
    ]
