# Generated by Django 4.0.3 on 2024-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_plandetail_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='num_of_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
