# Generated by Django 4.0.3 on 2023-06-26 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.PROTECT, related_name='employee_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
