# Generated by Django 4.0.3 on 2023-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_employeedocumentationwork_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeresignationdetails',
            name='last_working_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
