# Generated by Django 4.0.3 on 2023-08-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_alter_employeeworkdetails_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaddressdetails',
            name='other_house_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
