# Generated by Django 4.0.3 on 2023-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_sessionyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_sign_up',
            field=models.BooleanField(default=False),
        ),
    ]
