# Generated by Django 4.2 on 2023-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_alter_employee_is_sign_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocuments',
            name='document_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='document_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentstypes',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'PAN Card'), (20, 'Aadhaar Card'), (30, 'Passport'), (40, 'Driving Licence'), (50, 'Voter ID'), (60, 'Electricity Bill'), (70, 'Phone Bill'), (80, 'Bank Passbook'), (90, 'Rental Agreement'), (100, 'others')], verbose_name='Document Types'),
        ),
    ]
