# Generated by Django 4.2 on 2023-09-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_employeedocuments_document_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payroll_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
