# Generated by Django 4.2 on 2023-09-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_alter_employee_payroll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payroll_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
