# Generated by Django 4.0.3 on 2023-09-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_alter_employee_payroll_status'),
        ('directory', '0016_employeesalarydetails_fund_transfer_type'),
    ]

    operations = [
    ]
