# Generated by Django 4.0.3 on 2023-09-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_merge_20230921_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payroll_status',
            field=models.BooleanField(default=True),
        ),
    ]
