# Generated by Django 4.0.3 on 2023-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_alter_employee_payroll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payroll_entity',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_entity',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
