# Generated by Django 4.0.3 on 2023-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_employee_payroll_entity_employee_work_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarydetails',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeesalarydetails',
            name='variable_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
