# Generated by Django 4.2 on 2023-10-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_employeesalarydetails_fixed_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalarydetails',
            options={'verbose_name': 'Employee Salary Detail', 'verbose_name_plural': 'Employee Salary Details'},
        ),
    ]
