# Generated by Django 4.0.3 on 2023-10-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_alter_employeesalarydetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalarydetails',
            options={'ordering': ('created_at',), 'verbose_name': 'Employee Salary Detail', 'verbose_name_plural': 'Employee Salary Details'},
        ),
    ]
