# Generated by Django 4.0.3 on 2023-10-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0009_announcements_annoucement_image_and_more'),
        ('directory', '0022_alter_employeesalarydetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkhistorydetails',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_manager_history', to='directory.employee'),
        ),
        migrations.AlterField(
            model_name='employeeworkhistorydetails',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.departments'),
        ),
        migrations.AlterField(
            model_name='employeeworkhistorydetails',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.designations'),
        ),
        migrations.AlterField(
            model_name='employeeworkhistorydetails',
            name='work_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeworkhistorydetails',
            name='work_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
