# Generated by Django 4.0.3 on 2023-10-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_employeeworkhistorydetails_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['date_of_join'], 'verbose_name': 'Personal Details', 'verbose_name_plural': 'Personal Details'},
        ),
        migrations.AlterModelOptions(
            name='employeeaddressdetails',
            options={'verbose_name': 'Address Details', 'verbose_name_plural': 'Address Details'},
        ),
        migrations.AlterModelOptions(
            name='employeecertifications',
            options={'verbose_name': 'Educational Documents', 'verbose_name_plural': 'Educational Documets'},
        ),
        migrations.AlterModelOptions(
            name='employeedocumentationwork',
            options={'verbose_name': 'Work Docs', 'verbose_name_plural': 'Work Docs'},
        ),
        migrations.AlterModelOptions(
            name='employeeeducationdetails',
            options={'ordering': ('created_at',), 'verbose_name': 'Educational Info', 'verbose_name_plural': 'Educational Info'},
        ),
        migrations.AlterModelOptions(
            name='employeeemergencycontact',
            options={'ordering': ('created_at',), 'verbose_name': 'Emargency Contact', 'verbose_name_plural': 'Emargency Contact'},
        ),
        migrations.AlterModelOptions(
            name='employeefamilydetails',
            options={'ordering': ('created_at',), 'verbose_name': 'Family Details', 'verbose_name_plural': 'Family Details'},
        ),
        migrations.AlterModelOptions(
            name='employeeresignationdetails',
            options={'verbose_name': 'Resignation Info', 'verbose_name_plural': 'Resignation Info'},
        ),
        migrations.AlterModelOptions(
            name='employeesalarydetails',
            options={'ordering': ('created_at',), 'verbose_name': 'Salary/Bank Info', 'verbose_name_plural': 'Salary/Bank Info'},
        ),
        migrations.AlterModelOptions(
            name='employeeworkdetails',
            options={'get_latest_by': ['employee__created_at'], 'ordering': ['created_at'], 'verbose_name': 'Work Details', 'verbose_name_plural': 'Work Details'},
        ),
        migrations.AlterModelOptions(
            name='employeeworkhistorydetails',
            options={'verbose_name': 'Work History Detail', 'verbose_name_plural': 'Work History Details'},
        ),
        migrations.AlterModelOptions(
            name='relationshiptypes',
            options={'verbose_name': 'Relationship Type', 'verbose_name_plural': 'Relationship Types'},
        ),
    ]
