# Generated by Django 4.0.3 on 2023-10-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0024_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payroll_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
