# Generated by Django 4.0.3 on 2023-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_alter_employee_payroll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeresignationdetails',
            name='exit_interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeresignationdetails',
            name='exit_interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
