# Generated by Django 4.0.3 on 2023-10-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0026_employeeresignationdetails_exit_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarydetails',
            name='advance_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeesalarydetails',
            name='arrears',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeesalarydetails',
            name='montly_incentive',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeesalarydetails',
            name='special_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
