# Generated by Django 4.2 on 2023-10-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0026_employeeresignationdetails_exit_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeresignationdetails',
            name='reason_of_leaving',
            field=models.CharField(blank=True, choices=[('Resigned', 'Resigned'), ('Absconded', 'Absconded'), ('Terminated', 'Terminated')], default='Resigned', max_length=16, null=True),
        ),
    ]
