# Generated by Django 4.0.3 on 2023-10-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0027_employeesalarydetails_advance_deductions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalarydetails',
            old_name='montly_incentive',
            new_name='monthly_incentive',
        ),
    ]
