# Generated by Django 4.0.3 on 2023-11-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0028_employeeworkdetails_probation_period_left'),
        ('directory', '0028_rename_montly_incentive_employeesalarydetails_monthly_incentive'),
    ]

    operations = [
    ]
