# Generated by Django 4.0.3 on 2023-11-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0028_employeeworkdetails_probation_period_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeresignationdetails',
            name='reason_of_leaving',
            field=models.CharField(blank=True, choices=[('Resigned', 'Resigned'), ('Absconded', 'Absconded'), ('Terminated', 'Terminated'), ('ReJoined', 'ReJoined')], default='Resigned', max_length=16, null=True),
        ),
    ]
