# Generated by Django 4.0.3 on 2023-11-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0029_alter_employeeresignationdetails_reason_of_leaving'),
        ('directory', '0029_merge_20231110_1426'),
    ]

    operations = [
    ]
