# Generated by Django 4.0.3 on 2023-12-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0031_employeeexperiencedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperiencedetails',
            name='company_url',
            field=models.URLField(blank=True, max_length=80, null=True, verbose_name='Company URL'),
        ),
    ]
