# Generated by Django 4.0.3 on 2024-02-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0034_employeeworkhistorydetails_manager_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTCHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ctc_history', to='directory.employee')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_ctc_employee', to='directory.employee')),
            ],
        ),
    ]
