# Generated by Django 4.0.3 on 2024-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0034_employeeworkhistorydetails_manager_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='official_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Official Email'),
        ),
    ]
