# Generated by Django 4.2 on 2024-02-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0034_employeeworkhistorydetails_manager_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereportingmanager',
            name='is_multitenant',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Multitenant?'),
        ),
        migrations.AddField(
            model_name='employeereportingmanager',
            name='multitenant_manager_company',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employeereportingmanager',
            name='multitenant_manager_company_domain',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employeereportingmanager',
            name='multitenant_manager_emp_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employeereportingmanager',
            name='multitenant_manager_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='employeereportingmanager',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_manager', to='directory.employee'),
        ),
    ]
