# Generated by Django 4.2 on 2024-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0034_employeeworkhistorydetails_manager_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarydetails',
            name='previous_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalarydetails',
            name='previous_tds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
