# Generated by Django 4.2 on 2024-02-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0035_ctchistory'),
        ('directory', '0035_employeesalarydetails_previous_income_and_more'),
    ]

    operations = [
    ]
