# Generated by Django 4.2 on 2024-03-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0036_employeereportingmanager_multitenant_manager_email'),
        ('directory', '0036_merge_20240229_1559'),
    ]

    operations = [
    ]
