# Generated by Django 4.2 on 2024-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0037_merge_20240302_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkhistorydetails',
            name='is_multitenant_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeworkhistorydetails',
            name='multitenant_manager_company_domain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employeeworkhistorydetails',
            name='multitenant_manager_emp_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
