# Generated by Django 4.2 on 2024-03-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0038_employeeworkhistorydetails_is_multitenant_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocuments',
            name='is_uploaded_by_tenant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='tenant_company_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tenant Company ID'),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='tenant_domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tenant Domain'),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='tenant_user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
