# # Generated by Django 4.2 on 2024-03-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0038_employeeworkhistorydetails_is_multitenant_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
