# Generated by Django 4.0.3 on 2024-03-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0035_alter_employee_official_email'),
        ('directory', '0039_employee_bio'),
        ('directory', '0039_employeedocuments_is_uploaded_by_tenant_and_more'),
    ]

    operations = [
    ]
