# Generated by Django 4.2 on 2024-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0039_employeedocuments_is_uploaded_by_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarydetails',
            name='previous_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalarydetails',
            name='previous_tds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
