# Generated by Django 4.2 on 2024-03-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0040_alter_employeesalarydetails_previous_income_and_more'),
        ('directory', '0040_merge_20240317_1550'),
    ]

    operations = [
    ]
