# Generated by Django 4.2 on 2024-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0041_alter_ctchistory_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeworkdetails',
            index=models.Index(fields=['employee', 'employee_number', 'department', 'sub_department', 'designation', 'job_title', 'work_location', 'employee_grade', 'employee_type', 'employee_status', 'experience_in_years', 'experience_in_months', 'probation_period', 'probation_period_left'], name='work_details_table_index'),
        ),
    ]
