# Generated by Django 4.0.3 on 2024-04-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0041_alter_ctchistory_updated_at'),
        ('directory', '0041_merge_20240320_2021'),
    ]

    operations = [
    ]
