# Generated by Django 4.0.3 on 2024-04-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0042_merge_20240410_1210'),
        ('directory', '0042_merge_20240412_1751'),
    ]

    operations = [
    ]
