# Generated by Django 4.0.3 on 2024-04-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0043_merge_20240415_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_doc', models.FileField(upload_to='work_documents/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_work_doc_files', to='directory.employeedocumentationwork')),
            ],
        ),
    ]
