# Generated by Django 4.2 on 2024-04-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0045_companysmtpsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='added_from',
            field=models.CharField(default='HRMS', max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='al_digital_sign',
            field=models.FileField(blank=True, null=True, upload_to='al_digital_sign/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='appointment_letter',
            field=models.FileField(blank=True, null=True, upload_to='appointment_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='appointment_letter_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='appointment_letter_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='col_digital_sign',
            field=models.FileField(blank=True, null=True, upload_to='col_digital_sign/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='conditional_offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='conditional_offer_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='conditional_offer_letter_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='conditional_offer_letter_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_appointment_letter_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_bgv_complted',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_conditional_offer_letter_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_responding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rejection_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
