# Generated by Django 4.0.3 on 2024-04-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0046_employee_added_from_employee_al_digital_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_image',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='employee_images/'),
        ),
    ]
