# Generated by Django 4.2 on 2024-04-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0046_employee_added_from_employee_al_digital_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='al_date_of_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='al_ip_address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='col_date_of_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='col_ip_address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
