# Generated by Django 4.2 on 2024-04-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0046_employee_added_from_employee_al_digital_sign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateCheckInOutReminderCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_check_in', models.DateField()),
                ('is_late_check_in_reminder_sent', models.BooleanField(default=False)),
                ('is_late_check_out_reminder_sent', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forget_reminder', to='directory.employee')),
            ],
            options={
                'unique_together': {('employee', 'date_of_check_in')},
            },
        ),
    ]
