# Generated by Django 4.2 on 2024-04-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0047_alter_employee_employee_image'),
        ('directory', '0047_employee_al_date_of_update_employee_al_ip_address_and_more'),
        ('directory', '0047_latecheckinoutremindercheck'),
    ]

    operations = [
    ]
