# Generated by Django 4.2 on 2024-04-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0048_alter_employeecertifications_select_file_and_more'),
        ('directory', '0048_merge_20240429_1727'),
    ]

    operations = [
    ]
