# Generated by Django 4.2 on 2024-05-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0049_merge_20240429_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='al_sign',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='col_sign',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_welcome_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
