# Generated by Django 4.2 on 2024-05-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0042_employeeworkdetails_work_details_table_index'),
        ('directory', '0051_employee_appointment_letter_pdf_content_and_more'),
    ]

    operations = [
    ]
