# Generated by Django 4.2 on 2024-05-05 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0052_merge_20240505_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='added_from',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='al_date_of_update',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='al_digital_sign',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='al_ip_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='al_sign',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='appointment_letter',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='appointment_letter_content',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='appointment_letter_pdf_content',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='appointment_letter_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='col_date_of_update',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='col_digital_sign',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='col_ip_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='col_sign',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='conditional_offer_letter',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='conditional_offer_letter_content',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='conditional_offer_letter_pdf_content',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='conditional_offer_letter_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_appointment_letter_sent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_bgv_complted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_conditional_offer_letter_sent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_responding',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_welcome_mail_sent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rejection_comments',
        ),
        migrations.CreateModel(
            name='EmployeePreBoardingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_conditional_offer_letter_sent', models.BooleanField(default=False)),
                ('conditional_offer_letter_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('conditional_offer_letter', models.FileField(blank=True, null=True, upload_to='conditional_offer_letters/')),
                ('conditional_offer_letter_content', models.TextField(blank=True, null=True)),
                ('conditional_offer_letter_pdf_content', models.TextField(blank=True, null=True)),
                ('col_digital_sign', models.FileField(blank=True, null=True, upload_to='col_digital_sign/')),
                ('col_date_of_update', models.DateTimeField(blank=True, null=True)),
                ('col_ip_address', models.CharField(blank=True, max_length=32, null=True)),
                ('col_sign', models.CharField(blank=True, max_length=32, null=True)),
                ('is_appointment_letter_sent', models.BooleanField(default=False)),
                ('appointment_letter_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('appointment_letter', models.FileField(blank=True, null=True, upload_to='appointment_letters/')),
                ('appointment_letter_content', models.TextField(blank=True, null=True)),
                ('appointment_letter_pdf_content', models.TextField(blank=True, null=True)),
                ('al_digital_sign', models.FileField(blank=True, null=True, upload_to='al_digital_sign/')),
                ('al_date_of_update', models.DateTimeField(blank=True, null=True)),
                ('al_ip_address', models.CharField(blank=True, max_length=32, null=True)),
                ('al_sign', models.CharField(blank=True, max_length=32, null=True)),
                ('is_bgv_complted', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('added_from', models.CharField(default='HRMS', max_length=32)),
                ('rejection_comments', models.TextField(blank=True, null=True)),
                ('is_responding', models.BooleanField(default=True)),
                ('is_welcome_mail_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_boarding_details', to='directory.employee', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
