# Generated by Django 4.2 on 2024-02-06 13:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMSApp', '0022_merge_20240203_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('log_path', models.TextField()),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('db_name', models.CharField(max_length=256)),
                ('path', models.TextField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('interval', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16, null=True)),
                ('run_time', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=16, null=True), default=list, size=None)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None)),
                ('week_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=8, null=True), default=list, size=None)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('roles', models.ManyToManyField(default=[], to='HRMSApp.roles')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
