# Generated by Django 4.2 on 2024-02-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_calling_func'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='desc_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
