# Generated by Django 4.0.3 on 2024-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_desc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
