############## Company Profile #################

ROLES_INPUT={'modules':{'OrganizationProfile':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'Overview':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CompanyDetails',
'StatutoryDetails',
'CompanyDirectorDetails',
'BankDetails',
'CustomAddressDetails']},
'Directors':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CompanyDirectorDetails']},
'Auditors':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['AuditorDetails']},
'CompanySecretary':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['SecretaryDetails']},
'BankDetails':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['BankDetails']},
'RegisteredOfficeAddress':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CompanyDetails']},
'CorporateOfficeAddress':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CompanyDetails']},
'CustomOfficeAddress':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CustomAddressDetails']},
'PayrollSettings':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['AttendanceRuleSettings','LeaveRuleSettings','CompanyCustomizedConfigurations']},
'Grades':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CompanyGrades']},
'Designation':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Designations','Grade']},
'Department':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Departments','SubDepartments']},
'Organizationsetup':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CompanyDetails',
'CustomAddressDetails',
'StatutoryDetails',
'BankDetails',
'CompanyDirectorDetails',
'AuditorDetails',
'SecretaryDetails',
'Grade',
'AttendanceRuleSettings']},
'LeavesSetup':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['LeaveRuleSettings']},
'ShiftsSetup':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['AttendanceShiftsSetup']},
'AddGradeLable':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Grade']},
}},

######## Employee Management ############

'EmployeeManagement':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'Roles':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Roles']},
'BulkEdit':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee','EmployeeWorkDetails', 'EmployeeMonthlyAttendanceRecords']},
'Mail':{'add':False,'view':False,'change':False,'delete':False},
'Import':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee',
'EmployeeWorkDetails',
'EmployeeSalaryDetails',
'EmployeeEmergencyContact', 'EmployeeDocuments']},
'Export':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee',
'EmployeeWorkDetails',
'EmployeeSalaryDetails',
'EmployeeEmergencyContact']},
'Invite':{'add':False,'view':False,'change':False,'delete':False},
'EmployeeProfile':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee','EmployeeWorkDetails','EmployeeSalaryDetails', 'EmployeeMonthlyAttendanceRecords']},
'AddEmployee':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee','EmployeeWorkDetails','EmployeeSalaryDetails']},
'AddColumns':{'add':False,
'view':False,
'change':False,
'delete':False,},
'EmployeeRedirections':{'add':False,
'view':False,
'change':False,
'delete':False,},
'InActiveEmployees':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee']},
}},

############ My Profile ###############

'MyProfile':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'PersonalDetails':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee',
'EmployeeWorkDetails',
'EmployeeSalaryDetails',
'EmployeeAddressDetails',
'EmployeeWorkHistoryDetails',
'EmployeeResignationDetails',
'EmployeeReportingManager',
'EmployeeFamilyDetails',
'EmployeeEmergencyContact',
'EmployeeEducationDetails',
'EmployeeDocuments',
'EmployeeCertifications',
'EmployeeDocumentationWork',
'CompanyDetails',
'CustomAddressDetails',
'EmployeeExperienceDetails',
]},
'EmploymentDetails':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee',
'EmployeeWorkDetails',
'EmployeeSalaryDetails',
'EmployeeAddressDetails',
'EmployeeWorkHistoryDetails',
'EmployeeResignationDetails',
'EmployeeReportingManager',
'EmployeeFamilyDetails',
'EmployeeEmergencyContact',
'EmployeeEducationDetails',
'EmployeeDocuments',
'EmployeeCertifications',
'EmployeeDocumentationWork',
'EmployeeExperienceDetails',
]},
'Address':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['EmployeeAddressDetails','EmployeeDocuments']},
'Education':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['EmployeeEducationDetails','EmployeeCertifications']},
'Family':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['EmployeeFamilyDetails','EmployeeEmergencyContact']},
'BankDetails':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['EmployeeSalaryDetails','EmployeeComplianceNumbers']},
'WorkDetails':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee','EmployeeWorkDetails','EmployeeDocumentationWork','EmployeeResignationDetails','CompanyDetails','CustomAddressDetails','EmployeeExperienceDetails']},
'Team':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee','EmployeeWorkDetails','EmployeeReportingManager','Departments','Designations']},
'CompanyDocuments':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CompanyPolicyDocuments','CompanyPolicyTypes']},
'WorkWeek':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['WorkRules',
'WorkRuleChoices',
'EmployeeWorkRuleRelation']},
'Attendence':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AttendanceRules',
'EmployeeCheckInOutDetails',
'AssignedAttendanceRules','EmployeeLeaveRuleRelation']},
'LeaveManagement':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['LeaveRules','LeavesHistory','EmployeeLeaveRuleRelation']}}},

############## Saving Declaration ################

'SavingDeclaration':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'SavingDeclarationForm':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['InvestmentDeclaration','DeclarationForms','Attachments','Employee']},
'SavingDeclarationList':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['InvestmentDeclaration','DeclarationForms','Attachments']},
'EmployeesSavingDeclarationList':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['InvestmentDeclaration','DeclarationForms','Attachments']},
'SavingDeclarationDetails': {
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'models': []
},
'ApprovedDeclarationsList':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['InvestmentDeclaration','DeclarationForms','Attachments']},
'ReimbursementEmployeeView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Reimbursement']},
'ReimbursementEmployerView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Reimbursement']}}},

############## Monthly KRA #######################

'MonthlyKRA':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'AddQuestionnaire':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AppraisalSetName','AppraisalSetQuestions']},
'SendQuestionnaire':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AppraisalSendForm','AppraisalSetName']},
'AllInCheckFormList':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AppraisalSendForm','Departments']},
'NotificationDates':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['NotificationDates']},
'EmployeeKRA':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AppraisalFormSubmit','AppraisalSendForm']},
'ArchiveFolder':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AppraisalSendForm','Departments']},
'PerformaceFormEmployee':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AppraisalSendForm']}}},

############## Leave Module ##################Performace Form (Employee)

'LeaveModule':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'ApplyLeave':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['LeavesHistory','EmployeeLeaveRuleRelation']},
'LeaveHistoryUser':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['LeavesHistory']},
'CreateLeaveRule':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['LeaveRules']},
'AssignLeaveRule':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeLeaveRuleRelation','LeaveRules']},
'LeaveApprovals':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['LeavesHistory','Departments']},
'LeaveHistoryEmployees':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['LeavesHistory','LeaveRules','EmployeeLeaveRuleRelation']},
'Export':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CompanyDetails','LeavesHistory']},
'BulkApprove':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['LeavesHistory']},
'Approve':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['LeavesHistory']},
'Reject':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['LeavesHistory']},
'Cancel':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['LeavesHistory']},
'Export':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['EmployeeLeaveRuleRelation']},
'AddColumns':{'add':False,
'view':False,
'change':False,
'delete':False},
}},

############## Attendance Module ###################

'AttendenceModule':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'Check-in&Check-out':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeCheckInOutDetails']},
'CreateAttendanceRule':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AttendanceRules','PenaltyRules']},
'AssignAddendanceRule':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AssignedAttendanceRules','Employee','AttendanceRules']},
'AttendanceApprovals':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeCheckInOutDetails','AnamolyHistory','Employee']},
'Approve':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeCheckInOutDetails','AnamolyHistory']},
'Reject':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeCheckInOutDetails','AnamolyHistory']},
'Cancel':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeCheckInOutDetails','AnamolyHistory']},
'AttendanceHistory':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeCheckInOutDetails','Employee']},
'AttendaceHistoryEmployerview':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeCheckInOutDetails','AnamolyHistory']},
'AttendanceHistoryEmployeeView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeCheckInOutDetails','AnamolyHistory','Employee','EmployeeLeaveRuleRelation']},
'Export':{'add':False,
'view':False,
'change':False,
'delete':False,
'models':['CompanyDetails','EmployeeCheckInOutDetails','AnamolyHistory','Employee']},
'AttendanceRuleEmployee':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AssignedAttendanceRules','EmployeeWorkRuleRelation']},
'AttendanceResendReminder':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['AssignedAttendanceRules']},
'BulkApprove':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeCheckInOutDetails']},
'AttendanceReport':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee','EmployeeCheckInOutDetails']},
'AttendanceReportExport':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee','EmployeeCheckInOutDetails']},
}},


################ Work Week ##################

'WorkWeek':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
'CreateWorkWeek':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['WorkRules','WorkRuleChoices']},
'AssignWorkWeek':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['WorkRules','WorkRuleChoices','EmployeeWorkRuleRelation','Employee']},
'AssignWorkWeekEmployeeView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['WorkRules','WorkRuleChoices','EmployeeWorkRuleRelation','Employee']}
}},

################ Calendar ###################

'Calendar':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'UploadHolidays':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Holidays','Events']},
'AddEvents':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Events','Holidays']},
'HolidayList':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Holidays']},
'CreateWorkWeek':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['WorkRules','WorkRuleChoices']},
'AssignWorkWeek':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['WorkRules','WorkRuleChoices','EmployeeWorkRuleRelation','Employee']},
'AssignWorkWeekEmployeeView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['WorkRules','WorkRuleChoices','EmployeeWorkRuleRelation','Employee']},
'PostAnAnnouncement':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Announcements','Departments']}
}},

################### Announcement Module #####################

'Announcement':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
'PostAnAnnouncement':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Announcements','Departments']}}},

#################### Consolidate Report ############

'ConsolidateReport':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'ConsolidateReportEmployeeView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeMonthlyAttendanceRecords']},
'ConssolidateReportEmployerView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeMonthlyAttendanceRecords']},
'SaveButton':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeMonthlyAttendanceRecords']},
'UpdateButton':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['EmployeeMonthlyAttendanceRecords']}}},

################### Audit Report #####################

'AuditReport':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
'Export':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':['LoggingRecord','Employee']},
'ReportView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['LoggingRecord','Employee']}}},

################### Dynamic Report #####################

'DynamicReport':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
'EmployeeDynamicReportExport':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee']},
'EmployersDynamicReport':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee']}}},

################### Dash Boards ##################

'Dashboard':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
'AdminDashboard':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Holidays','Departments','AttendanceRules','AppraisalSendForm','Reimbursement','Employee','LeavesHistory','Announcements','AttendanceRules']},
'ManagerDashboard':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Holidays','Departments','AttendanceRules','AppraisalSendForm','Reimbursement','Employee','LeavesHistory','Announcements','AttendanceRules']},
'UserDashboard':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Events','AppraisalSendForm','Holidays','Employee','Holidays','EmployeeReportingManager','Announcements','EmployeeLeaveRuleRelation']}}},

#################### Reports ########################

'Reports':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
'SystemTrackView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee','KeyloggerAttendanceLogs']},
'SystemTrackExport':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee','KeyloggerAttendanceLogs']},
'BiometricReportView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee','EmployeeWorkDetails']},
'BiometricReportExport':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee','EmployeeWorkDetails']},
'AuditReportView':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['LoggingRecord','Employee']},
'AuditReportExport':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':['LoggingRecord','Employee']},
'EmployeeDynamicReport':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Employee']},
'EmployerDynamicReport':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee']},
'MissingEmployeeData':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':['Employee']}}},

#################### ATS #####################

'ATS':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
'ATS':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':[]}}},

#################### PaySlip #####################
'PaySlip':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
'PaySlip':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':[]}}},

#################### MULTITENANT #####################
'MULTITENANT':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
    'MULTITENANT':{
    'add':False,
    'view':False,
    'change':False,
    'delete':False,
    'models':[]}}
},       
#################### Support #####################

'Support':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
'OpenTickets':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':[]},
'PendingTickets':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':[]},
'ClosedTickets':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':[]},
'ReopenedTickets':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':[]},
'CreateTicket':{
'add':False,
'view':False,
'change':False,
'delete':False,
'models':[]}}},

#################### ONBOARDING #####################

'ONBOARDING':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{
    'Template':{
    'add':False,
    'view':False,
    'change':False,
    'delete':False,
    'models':['Template','OnBoardingModule','EmployeeOnboardStatus',
              'OnBoardingSubModule','OnBoardingTask','OnBoardingCheckList','EmployeeCheckList']
        },
    'EmployeesList':{
    'add':False,
    'view':False,
    'change':False,
    'delete':False,
    'models':['Employee','EmployeeWorkDetails']
        },
    'Onboarding':{
    'add':False,
    'view':False,
    'change':False,
    'delete':False,
    'models':['OnBoardingTask','OnBoardingCheckList','EmployeeCheckList','Template', 'OnBoardingSubModule', 'TaskType']
        }
}
},

################### Settings #####################

'Settings':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'Roles':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Roles',
'RolesModules',
'RolesSubModule',
'RolesSubmoduleAttachModels',
'RoleModuleMapping',
'ModuleSubmoduleMapping',
'RoleSubmoduleModelMapping',
'SubModuleModelLeavelMapping']},
'Permissions':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Permission']},
'CompanyPolicies':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['CompanyPolicyDocuments','CompanyPolicyTypes']},
'Alerts':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Alert']},
'SMTP':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['CompanySMTPSetup']},
}},

################### Payroll #####################

# 'Payroll':{'add':False,
# 'view':False,
# 'delete':False,
# 'change':False,
# 'submodules':{'PayrollComponent':{
#                                     'add':False,
#                                     'view':False,
#                                     'delete':False,
#                                     'change':False,
#                                     'models':['EpfSetup','Esi','ProfessionTax','PaySalaryComponents']
#                                 }                
#               }
# }

##### payroll dashboards ####
'payrolldashboard':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'payrolldashboard':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
                }
    },

'payrollmaster':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'organizationdetails':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'taxdetails':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'statutorycompaonents':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'epf':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'esi':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'pt':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'setupsalrycomponts':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'addemployeedetails':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
                },
},

'payrollwatermark':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'watermarksignature':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
                },
},

'payrollorganizationsetup':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'organization':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'department':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'desigantion':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'mastersetup':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
                },
},

'payrollcomponent':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'Employeeprovidedfund':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'Employeestateinsurance':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'professionaltax':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'salarycomponents':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollemployees':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'activeemployees':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'manageemployees':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'importleavelop':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'importovertimepay':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'importvariablepay':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},


###payroll saving decarations####
'payrolldeclarations':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'declarationsetup':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'employerapprovals':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'reimbursement':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

#####payroll reports##########
'payrollstatutoryreports':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'payrolloverview':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'statutoryreports':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
        'employeereports':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollgratutyreports':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'payrollgratutyreport':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollmonthlytdsreport':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'payrollmonthlytdsreport':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollmissinginforeport':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'payrollmissinginforeport':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollsalaryinfo':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'payrollsalaryinfo':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollvariancereport':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'payrollvariancereport':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollauditreport':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'payrollauditreport':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollleavereport':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'leavereport':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollcompliancereport':{
    'add':False,
    'view':False,
    'delete':False,
    'change':False,
    'submodules':{
        'compliancereport':{'add':False, 'view':False, 'delete':False, 'change':False, 'models':[]},
    },
},

'payrollSettings':{'add':False,
'view':False,
'delete':False,
'change':False,
'submodules':{'Roles':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Roles',
'RolesModules',
'RolesSubModule',
'RolesSubmoduleAttachModels',
'RoleModuleMapping',
'ModuleSubmoduleMapping',
'RoleSubmoduleModelMapping',
'SubModuleModelLeavelMapping']},
'Permissions':{'add':False,
'view':False,
'delete':False,
'change':False,
'models':['Permission']}}}}}