# Generated by Django 4.0.3 on 2023-08-09 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0007_grade'),
        ('performance_management', '0002_alter_notificationdates_employees_kra_deadline_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdates',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Notification Will Use To Reminder Mail Of Monthly KRA', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_date', to='HRMSApp.companydetails', verbose_name='Notification'),
        ),
    ]
