# Generated by Django 4.0.3 on 2023-09-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0003_notificationdates_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalsendform',
            name='revoke',
        ),
        migrations.AddField(
            model_name='appraisalsendform',
            name='form_deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalsendform',
            name='is_revoked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
