# Generated by Django 4.0.3 on 2023-11-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0005_alter_appraisalformsubmit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalsendform',
            name='comment',
            field=models.TextField(help_text='Comment Will Be Add To An Employee By Manager', verbose_name='Comment'),
        ),
    ]
